###

POST http://localhost:9700/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "nombre":"dayanne" ,
  "apellido":"moque" ,
  "usuario": "dayanne112",
  "correo":"dayannemz@gmail.com",
  "contrasena":"123dayanne",
  "documento":"1025533562" ,
  "telefono": "3122567578"
}

###

GET http://localhost:9700/api/auth/register HTTP/1.1

###

GET http://localhost:9700/api/contactos/67375e9a11528262c31b62f1 HTTP/1.1

###

DELETE http://localhost:9700/api/contactos/6737605f11528262c31b62f6 HTTP/1.1

###