###

POST http://localhost:7700/api/comida HTTP/1.1
Content-Type: application/json

{    
    "nombre": "Casuela de mariscos",
    "descripcion": "En la costa se brinda casuela para mejor experiencia",
    "precio": "25000",
    "categoria": "Mar"

}

###

GET http://localhost:7700/api/comida HTTP/1.1

###

GET http://localhost:7700/api/comida/67586a3f17c99cb8a3afed4b HTTP/1.1

###

DELETE http://localhost:7700/api/comida/67586a3f17c99cb8a3afed4b HTTP/1.1

